matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode9.4

language: node_js
node_js:
  - "10.15.1"
sudo: required

cache:
  directories:
    - node_modules

install:
- npm install
- npm install -g codecov

script:
  - npm test
  - npm run lint

after_success:
- bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION

